import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivityKind } from '../core/models';
import { TripStore } from '../core/trip-store.service';

@Component({ selector: 'app-places', imports: [ReactiveFormsModule], template: `
<section class="page"><div class="page-heading"><div><p class="eyebrow">Pequeñas semillas</p><h1>Lugares guardados</h1><p>Una colección de direcciones que todavía no has vivido, pero ya imaginas.</p></div><button class="button coral" (click)="showForm.set(true)">+ Guardar lugar</button></div><div class="filters"><input type="search" placeholder="Buscar por lugar o ciudad" [value]="query()" (input)="query.set($any($event.target).value)"><select [value]="category()" (change)="category.set($any($event.target).value)"><option value="todas">Todas las categorías</option><option value="cultura">Cultura</option><option value="comida">Comida</option><option value="naturaleza">Naturaleza</option><option value="alojamiento">Alojamiento</option></select><select [value]="visited()" (change)="visited.set($any($event.target).value)"><option value="todos">Por visitar y visitados</option><option value="pendiente">Por visitar</option><option value="visitado">Ya visitados</option></select></div>
@if(filtered().length){<div class="places">@for(place of filtered();track place.id){<article class="place" [class.visited]="place.visited"><img [src]="place.image" [alt]="place.name"><div><span class="place-category">{{place.category}}</span><h2>{{place.name}}</h2><p>{{place.city}}, {{place.country}}</p><blockquote>{{place.note}}</blockquote><button class="visit" (click)="store.togglePlace(place.id)"><span>{{place.visited?'✓':''}}</span>{{place.visited?'Visitado':'Marcar como visitado'}}</button></div></article>}</div>}@else{<div class="empty"><h2>Ningún lugar por aquí</h2><p>Prueba otro filtro o guarda una nueva dirección.</p></div>}
</section>
@if(showForm()){<div class="modal-backdrop" (click)="closeForm()"><form class="modal" [formGroup]="form" (ngSubmit)="save()" (click)="$event.stopPropagation()"><header><div><p class="eyebrow">Para otro día</p><h2>Guardar un lugar</h2></div><button class="icon-button" type="button" (click)="closeForm()">×</button></header><div class="form-grid"><div class="field"><label for="place-name">Nombre</label><input id="place-name" formControlName="name" placeholder="Ej. Casa Milà"></div><div class="field"><label for="place-city">Ciudad</label><input id="place-city" formControlName="city" placeholder="Ej. Barcelona"></div><div class="field"><label for="place-country">País</label><input id="place-country" formControlName="country" placeholder="Ej. España"></div><div class="field"><label for="place-category">Categoría</label><select id="place-category" formControlName="category"><option value="cultura">Cultura</option><option value="comida">Comida</option><option value="naturaleza">Naturaleza</option><option value="alojamiento">Alojamiento</option><option value="otro">Otro</option></select></div><div class="field full"><label for="place-image">Imagen (URL)</label><input id="place-image" formControlName="image"></div><div class="field full"><label for="place-note">Nota</label><textarea id="place-note" formControlName="note" placeholder="¿Por qué quieres ir?"></textarea></div></div>@if(store.error()){<p class="error" role="alert">{{store.error()}}</p>}<footer><button class="button secondary" type="button" (click)="closeForm()">Cancelar</button><button class="button coral" [disabled]="saving()">{{saving()?'Guardando…':'Guardar lugar'}}</button></footer></form></div>}
`, styles: `.places{display:grid;gap:1.25rem;grid-template-columns:repeat(3,1fr)}.place{background:var(--paper);border:1px solid var(--line);overflow:hidden}.place>img{aspect-ratio:1.15;display:block;filter:saturate(.9);object-fit:cover;width:100%}.place>div{padding:1.2rem}.place-category{color:var(--coral);font-size:.68rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.place h2{font-size:1.75rem;margin:.55rem 0 .1rem}.place p{color:var(--muted);font-size:.8rem;margin:0}.place blockquote{border-left:2px solid var(--sand);color:var(--muted);font-family:var(--font-display);font-size:.95rem;font-style:italic;margin:1rem 0;padding-left:.7rem}.visit{background:transparent;border:0;color:var(--ink);font-size:.76rem;font-weight:700;padding:0}.visit span{border:1px solid var(--ink);border-radius:50%;display:inline-block;height:15px;line-height:13px;margin-right:.35rem;text-align:center;width:15px}.visited{opacity:.7}.visited img{filter:grayscale(.55)}.visited .visit span{background:var(--ink);color:white}@media(max-width:850px){.places{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.places{grid-template-columns:1fr}}` })
export class PlacesPage { readonly store=inject(TripStore);private readonly fb=inject(FormBuilder);readonly query=signal('');readonly category=signal('todas');readonly visited=signal('todos');readonly showForm=signal(false);readonly saving=signal(false);readonly filtered=computed(()=>this.store.places().filter(place=>(this.category()==='todas'||place.category===this.category())&&(this.visited()==='todos'||this.visited()==='visitado'&&place.visited||this.visited()==='pendiente'&&!place.visited)&&(`${place.name} ${place.city} ${place.country}`.toLowerCase().includes(this.query().toLowerCase()))));readonly form=this.fb.nonNullable.group({name:['',Validators.required],city:['',Validators.required],country:['',Validators.required],category:['cultura' as ActivityKind],image:['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=75',Validators.required],note:['']});closeForm(){if(!this.saving())this.showForm.set(false)}async save(){if(this.form.invalid){this.form.markAllAsTouched();return}this.saving.set(true);try{await this.store.addPlace({...this.form.getRawValue(),visited:false});this.form.reset({name:'',city:'',country:'',category:'cultura',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=800&q=75',note:''})}catch{}finally{this.saving.set(false);if(!this.store.error())this.showForm.set(false)}} }
