/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiItineraryDraftDto } from '../../models/ai-itinerary-draft-dto';
import { GenerateItineraryDto } from '../../models/generate-itinerary-dto';

export interface AiControllerGenerate$Params {
  tripId: string;
      body: GenerateItineraryDto
}

export function aiControllerGenerate(http: HttpClient, rootUrl: string, params: AiControllerGenerate$Params, context?: HttpContext): Observable<StrictHttpResponse<AiItineraryDraftDto>> {
  const rb = new RequestBuilder(rootUrl, aiControllerGenerate.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiItineraryDraftDto>;
    })
  );
}

aiControllerGenerate.PATH = '/trips/{tripId}/ai-itinerary';
