/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeocodeSearchResponseDto } from '../../models/geocode-search-response-dto';

export interface GeocodingControllerSearch$Params {
  q: string;
}

export function geocodingControllerSearch(http: HttpClient, rootUrl: string, params: GeocodingControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<GeocodeSearchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, geocodingControllerSearch.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeocodeSearchResponseDto>;
    })
  );
}

geocodingControllerSearch.PATH = '/geo/search';
