/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicConfigResponseDto } from '../../models/public-config-response-dto';

export interface PublicConfigControllerGetPublicConfig$Params {
}

export function publicConfigControllerGetPublicConfig(http: HttpClient, rootUrl: string, params?: PublicConfigControllerGetPublicConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicConfigResponseDto>> {
  const rb = new RequestBuilder(rootUrl, publicConfigControllerGetPublicConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicConfigResponseDto>;
    })
  );
}

publicConfigControllerGetPublicConfig.PATH = '/config/public';
