/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MediaSearchResultDto } from '../../models/media-search-result-dto';

export interface MediaControllerSearch$Params {
  q: string;
}

export function mediaControllerSearch(http: HttpClient, rootUrl: string, params: MediaControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MediaSearchResultDto>>> {
  const rb = new RequestBuilder(rootUrl, mediaControllerSearch.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MediaSearchResultDto>>;
    })
  );
}

mediaControllerSearch.PATH = '/media/search';
