/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MediaAssetResponseDto } from '../../models/media-asset-response-dto';

export interface MediaControllerImportOpenverse$Params {
  openverseId: string;
}

export function mediaControllerImportOpenverse(http: HttpClient, rootUrl: string, params: MediaControllerImportOpenverse$Params, context?: HttpContext): Observable<StrictHttpResponse<MediaAssetResponseDto>> {
  const rb = new RequestBuilder(rootUrl, mediaControllerImportOpenverse.PATH, 'post');
  if (params) {
    rb.path('openverseId', params.openverseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MediaAssetResponseDto>;
    })
  );
}

mediaControllerImportOpenverse.PATH = '/media/openverse/{openverseId}';
