/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripResponseDto } from '../../models/trip-response-dto';

export interface TripsControllerList$Params {
}

export function tripsControllerList(http: HttpClient, rootUrl: string, params?: TripsControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TripResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerList.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TripResponseDto>>;
    })
  );
}

tripsControllerList.PATH = '/trips';
