/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItineraryDayResponseDto } from '../../models/itinerary-day-response-dto';

export interface TripsControllerDays$Params {
  tripId: string;
}

export function tripsControllerDays(http: HttpClient, rootUrl: string, params: TripsControllerDays$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItineraryDayResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerDays.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ItineraryDayResponseDto>>;
    })
  );
}

tripsControllerDays.PATH = '/trips/{tripId}/days';
