/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItineraryDayResponseDto } from '../../models/itinerary-day-response-dto';
import { ReorderActivitiesDto } from '../../models/reorder-activities-dto';

export interface TripsControllerReorder$Params {
  dayId: string;
      body: ReorderActivitiesDto
}

export function tripsControllerReorder(http: HttpClient, rootUrl: string, params: TripsControllerReorder$Params, context?: HttpContext): Observable<StrictHttpResponse<ItineraryDayResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerReorder.PATH, 'put');
  if (params) {
    rb.path('dayId', params.dayId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItineraryDayResponseDto>;
    })
  );
}

tripsControllerReorder.PATH = '/days/{dayId}/activities/reorder';
