/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityResponseDto } from '../../models/activity-response-dto';
import { CreateActivityDto } from '../../models/create-activity-dto';

export interface TripsControllerAddActivity$Params {
  dayId: string;
      body: CreateActivityDto
}

export function tripsControllerAddActivity(http: HttpClient, rootUrl: string, params: TripsControllerAddActivity$Params, context?: HttpContext): Observable<StrictHttpResponse<ActivityResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerAddActivity.PATH, 'post');
  if (params) {
    rb.path('dayId', params.dayId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActivityResponseDto>;
    })
  );
}

tripsControllerAddActivity.PATH = '/days/{dayId}/activities';
