/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTripDto } from '../../models/create-trip-dto';
import { TripResponseDto } from '../../models/trip-response-dto';

export interface TripsControllerCreate$Params {
      body: CreateTripDto
}

export function tripsControllerCreate(http: HttpClient, rootUrl: string, params: TripsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponseDto>;
    })
  );
}

tripsControllerCreate.PATH = '/trips';
