/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripResponseDto } from '../../models/trip-response-dto';
import { UpdateTripDto } from '../../models/update-trip-dto';

export interface TripsControllerUpdate$Params {
  tripId: string;
      body: UpdateTripDto
}

export function tripsControllerUpdate(http: HttpClient, rootUrl: string, params: TripsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponseDto>;
    })
  );
}

tripsControllerUpdate.PATH = '/trips/{tripId}';
