/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateExpenseDto } from '../../models/create-expense-dto';
import { ExpenseResponseDto } from '../../models/expense-response-dto';

export interface TripsControllerAddExpense$Params {
  tripId: string;
      body: CreateExpenseDto
}

export function tripsControllerAddExpense(http: HttpClient, rootUrl: string, params: TripsControllerAddExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerAddExpense.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseResponseDto>;
    })
  );
}

tripsControllerAddExpense.PATH = '/trips/{tripId}/expenses';
