/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface TripsControllerDetachPlace$Params {
  tripId: string;
  placeId: string;
}

export function tripsControllerDetachPlace(http: HttpClient, rootUrl: string, params: TripsControllerDetachPlace$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerDetachPlace.PATH, 'delete');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('placeId', params.placeId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

tripsControllerDetachPlace.PATH = '/trips/{tripId}/places/{placeId}';
