/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SavedPlaceResponseDto } from '../../models/saved-place-response-dto';

export interface TripsControllerAttachPlace$Params {
  tripId: string;
  placeId: string;
}

export function tripsControllerAttachPlace(http: HttpClient, rootUrl: string, params: TripsControllerAttachPlace$Params, context?: HttpContext): Observable<StrictHttpResponse<SavedPlaceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerAttachPlace.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('placeId', params.placeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SavedPlaceResponseDto>;
    })
  );
}

tripsControllerAttachPlace.PATH = '/trips/{tripId}/places/{placeId}';
