/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityResponseDto } from '../../models/activity-response-dto';
import { UpdateActivityDto } from '../../models/update-activity-dto';

export interface TripsControllerUpdateActivity$Params {
  activityId: string;
      body: UpdateActivityDto
}

export function tripsControllerUpdateActivity(http: HttpClient, rootUrl: string, params: TripsControllerUpdateActivity$Params, context?: HttpContext): Observable<StrictHttpResponse<ActivityResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerUpdateActivity.PATH, 'patch');
  if (params) {
    rb.path('activityId', params.activityId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActivityResponseDto>;
    })
  );
}

tripsControllerUpdateActivity.PATH = '/activities/{activityId}';
