/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseResponseDto } from '../../models/expense-response-dto';
import { UpdateExpenseDto } from '../../models/update-expense-dto';

export interface TripsControllerUpdateExpense$Params {
  expenseId: string;
      body: UpdateExpenseDto
}

export function tripsControllerUpdateExpense(http: HttpClient, rootUrl: string, params: TripsControllerUpdateExpense$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerUpdateExpense.PATH, 'patch');
  if (params) {
    rb.path('expenseId', params.expenseId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseResponseDto>;
    })
  );
}

tripsControllerUpdateExpense.PATH = '/expenses/{expenseId}';
