/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityResponseDto } from '../../models/activity-response-dto';
import { BatchActivitiesDto } from '../../models/batch-activities-dto';

export interface TripsControllerBatch$Params {
  tripId: string;
      body: BatchActivitiesDto
}

export function tripsControllerBatch(http: HttpClient, rootUrl: string, params: TripsControllerBatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivityResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerBatch.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActivityResponseDto>>;
    })
  );
}

tripsControllerBatch.PATH = '/trips/{tripId}/activities/batch';
