/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripResponseDto } from '../../models/trip-response-dto';

export interface TripsControllerGet$Params {
  tripId: string;
}

export function tripsControllerGet(http: HttpClient, rootUrl: string, params: TripsControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TripResponseDto>> {
  const rb = new RequestBuilder(rootUrl, tripsControllerGet.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripResponseDto>;
    })
  );
}

tripsControllerGet.PATH = '/trips/{tripId}';
