/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInvitationDto } from '../../models/create-invitation-dto';
import { InvitationResponseDto } from '../../models/invitation-response-dto';

export interface InvitationsControllerCreate$Params {
      body: CreateInvitationDto
}

export function invitationsControllerCreate(http: HttpClient, rootUrl: string, params: InvitationsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, invitationsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationResponseDto>;
    })
  );
}

invitationsControllerCreate.PATH = '/admin/invitations';
