/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvitationResponseDto } from '../../models/invitation-response-dto';

export interface InvitationsControllerRenew$Params {
  invitationId: string;
}

export function invitationsControllerRenew(http: HttpClient, rootUrl: string, params: InvitationsControllerRenew$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, invitationsControllerRenew.PATH, 'post');
  if (params) {
    rb.path('invitationId', params.invitationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationResponseDto>;
    })
  );
}

invitationsControllerRenew.PATH = '/admin/invitations/{invitationId}/renew';
