/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InspectInvitationDto } from '../../models/inspect-invitation-dto';
import { InvitationInspectionDto } from '../../models/invitation-inspection-dto';

export interface InvitationsControllerInspect$Params {
      body: InspectInvitationDto
}

export function invitationsControllerInspect(http: HttpClient, rootUrl: string, params: InvitationsControllerInspect$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationInspectionDto>> {
  const rb = new RequestBuilder(rootUrl, invitationsControllerInspect.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationInspectionDto>;
    })
  );
}

invitationsControllerInspect.PATH = '/auth/invitations/inspect';
