import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Trip, TripStatus } from '../core/models';
import { TripStore } from '../core/trip-store.service';

@Component({ selector: 'app-trips', imports: [RouterLink, CurrencyPipe, DatePipe, ReactiveFormsModule], template: `
<section class="page"><div class="page-heading"><div><p class="eyebrow">Mi atlas personal</p><h1>Mis viajes</h1><p>Ideas que maduran, salidas que se acercan y recuerdos que ya forman parte de ti.</p></div><button class="button coral" (click)="openCreate()">+ Nuevo viaje</button></div>
<div class="filters"><input type="search" placeholder="Buscar destino" [value]="query()" (input)="query.set($any($event.target).value)"><select [value]="status()" (change)="status.set($any($event.target).value)"><option value="todos">Todos los estados</option><option value="planificando">Planificando</option><option value="proximo">Próximos</option><option value="completado">Completados</option></select></div>
@if(filtered().length){<div class="trips">@for(trip of filtered();track trip.id){<article class="trip"><img [src]="trip.coverImage" [alt]="trip.destination"><div class="trip-copy"><span class="status" [class]="'status '+trip.status">{{trip.status}}</span><h2>{{trip.destination}}</h2><p class="country">{{trip.country}} · {{trip.startDate | date:'d MMM yyyy'}} — {{trip.endDate | date:'d MMM yyyy'}}</p><p>{{trip.description}}</p><div class="trip-footer"><strong>{{trip.budget | currency:'EUR':'symbol':'1.0-0'}}</strong><div><button class="icon-button" (click)="openEdit(trip)" [attr.aria-label]="'Editar '+trip.destination">✎</button><a class="button small" [routerLink]="['/viajes',trip.id]">Abrir →</a></div></div></div></article>}</div>}@else{<div class="empty"><h2>No encontramos ese viaje</h2><p>Prueba con otro filtro o crea una nueva escapada.</p></div>}
</section>
@if(showForm()){<div class="modal-backdrop" (click)="closeForm()"><form class="modal" [formGroup]="form" (ngSubmit)="save()" (click)="$event.stopPropagation()"><header><div><p class="eyebrow">{{editing()?'Actualizar viaje':'Una nueva historia'}}</p><h2>{{editing()?'Editar viaje':'Crear un viaje'}}</h2></div><button class="icon-button" type="button" (click)="closeForm()" aria-label="Cerrar">×</button></header><div class="form-grid"><div class="field"><label for="destination">Destino</label><input id="destination" formControlName="destination" placeholder="Ej. Lisboa">@if(form.controls.destination.touched&&form.controls.destination.invalid){<span class="error">Indica un destino.</span>}</div><div class="field"><label for="country">País</label><input id="country" formControlName="country" placeholder="Ej. Portugal"></div><div class="field"><label for="start">Salida</label><input id="start" type="date" formControlName="startDate"></div><div class="field"><label for="end">Regreso</label><input id="end" type="date" formControlName="endDate"></div><div class="field"><label for="budget">Presupuesto (€)</label><input id="budget" type="number" min="0" formControlName="budget"></div><div class="field"><label for="status">Estado</label><select id="status" formControlName="status"><option value="planificando">Planificando</option><option value="proximo">Próximo</option><option value="completado">Completado</option></select></div><div class="field full"><label for="image">URL de imagen de portada</label><input id="image" formControlName="coverImage"></div><div class="field full"><label for="desc">Una nota sobre el viaje</label><textarea id="desc" formControlName="description"></textarea></div></div><footer><button class="button secondary" type="button" (click)="closeForm()">Cancelar</button><button class="button coral" type="submit">{{editing()?'Guardar cambios':'Crear viaje'}}</button></footer></form></div>}
`, styles: `.trips{display:grid;gap:1.25rem;grid-template-columns:repeat(2,minmax(0,1fr))}.trip{background:var(--paper);border:1px solid var(--line);display:grid;grid-template-columns:42% 1fr;min-height:300px}.trip>img{height:100%;object-fit:cover;width:100%}.trip-copy{padding:1.45rem}.trip h2{font-size:2rem;margin:.75rem 0 .15rem}.trip p{color:var(--muted);font-size:.88rem;line-height:1.5}.trip .country{font-size:.75rem}.trip-footer{align-items:center;border-top:1px solid var(--line);display:flex;justify-content:space-between;margin-top:1.4rem;padding-top:1rem}.trip-footer strong{font-family:var(--font-display);font-size:1.35rem}@media(max-width:850px){.trips{grid-template-columns:1fr}}@media(max-width:440px){.trip{grid-template-columns:1fr}.trip>img{aspect-ratio:1.6;height:auto}}` })
export class TripsPage { readonly store=inject(TripStore); private readonly fb=inject(FormBuilder); readonly query=signal('');readonly status=signal('todos');readonly showForm=signal(false);readonly editing=signal<Trip|null>(null);readonly filtered=computed(()=>this.store.trips().filter(t=>(this.status()==='todos'||t.status===this.status())&&(`${t.destination} ${t.country}`.toLowerCase().includes(this.query().toLowerCase())))); readonly form=this.fb.nonNullable.group({destination:['',Validators.required],country:['',Validators.required],startDate:['',Validators.required],endDate:['',Validators.required],budget:[0,[Validators.required,Validators.min(0)]],status:['planificando' as TripStatus],coverImage:['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85',Validators.required],description:['']}); openCreate(){this.editing.set(null);this.form.reset({destination:'',country:'',startDate:'',endDate:'',budget:0,status:'planificando',coverImage:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85',description:''});this.showForm.set(true)}openEdit(t:Trip){this.editing.set(t);this.form.reset(t);this.showForm.set(true)}closeForm(){this.showForm.set(false)}save(){if(this.form.invalid){this.form.markAllAsTouched();return}const value=this.form.getRawValue();const current=this.editing();if(current)this.store.updateTrip({...value,id:current.id});else this.store.createTrip(value);this.closeForm()} }
