/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripShareResponseDto } from '../../models/trip-share-response-dto';

export interface SharingControllerList$Params {
  tripId: string;
}

export function sharingControllerList(http: HttpClient, rootUrl: string, params: SharingControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TripShareResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, sharingControllerList.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TripShareResponseDto>>;
    })
  );
}

sharingControllerList.PATH = '/trips/{tripId}/shares';
