/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripShareResponseDto } from '../../models/trip-share-response-dto';
import { UpdateTripShareDto } from '../../models/update-trip-share-dto';

export interface SharingControllerUpdate$Params {
  tripId: string;
  shareId: string;
      body: UpdateTripShareDto
}

export function sharingControllerUpdate(http: HttpClient, rootUrl: string, params: SharingControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<TripShareResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sharingControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('shareId', params.shareId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripShareResponseDto>;
    })
  );
}

sharingControllerUpdate.PATH = '/trips/{tripId}/shares/{shareId}';
