/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TripShareResponseDto } from '../../models/trip-share-response-dto';

export interface SharingControllerRenew$Params {
  tripId: string;
  shareId: string;
}

export function sharingControllerRenew(http: HttpClient, rootUrl: string, params: SharingControllerRenew$Params, context?: HttpContext): Observable<StrictHttpResponse<TripShareResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sharingControllerRenew.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('shareId', params.shareId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripShareResponseDto>;
    })
  );
}

sharingControllerRenew.PATH = '/trips/{tripId}/shares/{shareId}/renew';
