/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SharedTripResponseDto } from '../../models/shared-trip-response-dto';

export interface SharingControllerPrivateView$Params {
  shareId: string;
}

export function sharingControllerPrivateView(http: HttpClient, rootUrl: string, params: SharingControllerPrivateView$Params, context?: HttpContext): Observable<StrictHttpResponse<SharedTripResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sharingControllerPrivateView.PATH, 'get');
  if (params) {
    rb.path('shareId', params.shareId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SharedTripResponseDto>;
    })
  );
}

sharingControllerPrivateView.PATH = '/shared-trips/{shareId}';
