/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTripShareDto } from '../../models/create-trip-share-dto';
import { TripShareResponseDto } from '../../models/trip-share-response-dto';

export interface SharingControllerCreate$Params {
  tripId: string;
      body: CreateTripShareDto
}

export function sharingControllerCreate(http: HttpClient, rootUrl: string, params: SharingControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TripShareResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sharingControllerCreate.PATH, 'post');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TripShareResponseDto>;
    })
  );
}

sharingControllerCreate.PATH = '/trips/{tripId}/shares';
