/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountDataDto } from '../models/account-data-dto';
import { UserResponseDto } from '../models/user-response-dto';
export interface AccountExportDto {
  account: UserResponseDto;
  data: AccountDataDto;
  exportedAt: string;
  schemaVersion: number;
}
