/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseResponseDto } from '../models/expense-response-dto';
import { ItineraryDayResponseDto } from '../models/itinerary-day-response-dto';
import { SavedPlaceResponseDto } from '../models/saved-place-response-dto';
import { TripResponseDto } from '../models/trip-response-dto';
export interface AccountDataDto {
  days: Array<ItineraryDayResponseDto>;
  expenses: Array<ExpenseResponseDto>;
  places: Array<SavedPlaceResponseDto>;
  trips: Array<TripResponseDto>;
}
