/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityResponseDto {
  completed: boolean;
  cost?: number;
  id: string;
  kind: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  notes: string;
  position: number;
  time: string;
  title: string;
}
