/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityResponseDto {
  address?: string | null;
  completed: boolean;
  cost?: number;
  id: string;
  kind: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  latitude?: number | null;
  locationName?: string | null;
  longitude?: number | null;
  notes: string;
  position: number;
  savedPlaceId?: string | null;
  time: string;
  title: string;
  travelModeToNext: 'walking' | 'cycling' | 'driving';
}
