/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DraftDayDto } from '../models/draft-day-dto';
export interface AiItineraryDraftDto {
  days: Array<DraftDayDto>;
  disclaimer: string;
}
