/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponseDto } from '../models/user-response-dto';
export interface AuthResponseDto {
  accessToken: string;
  user: UserResponseDto;
}
