/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BatchActivityItemDto } from '../models/batch-activity-item-dto';
export interface BatchActivitiesDto {
  activities: Array<BatchActivityItemDto>;
}
