/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSavedPlaceDto {
  address?: string | null;
  category: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  city: string;
  country: string;
  /** @deprecated */image?: string;
  imageAssetId?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  name: string;
  note: string;
  visited?: boolean;
}
