/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTripDto {
  budget: number;
  country: string;
  coverAssetId?: string | null;
  /** @deprecated */coverImage?: string;
  description: string;
  destination: string;
  endDate: string;
  startDate: string;
  status: 'planificando' | 'proximo' | 'completado';
}
