/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateActivityDto {
  completed?: boolean;
  cost?: number;
  kind: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  notes: string;
  time: string;
  title: string;
}
