/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExpenseDto {
  amount: number;
  category: 'alojamiento' | 'transporte' | 'comida' | 'experiencias' | 'compras' | 'otro';
  date: string;
  title: string;
}
