/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSavedPlaceDto {
  category: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  city: string;
  country: string;
  image: string;
  name: string;
  note: string;
  visited?: boolean;
}
