/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateActivityDto {
  address?: string | null;
  completed?: boolean;
  cost?: number;
  kind: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  latitude?: number | null;
  locationName?: string | null;
  longitude?: number | null;
  notes: string;
  savedPlaceId?: string | null;
  time: string;
  title: string;
}
