/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RouteLegResponseDto } from '../models/route-leg-response-dto';
export interface DayRouteResponseDto {
  attribution: string;
  dayId: string;
  disclaimer: string;
  generatedAt: string;
  legs: Array<RouteLegResponseDto>;
  provider: 'openrouteservice' | 'mock';
  status: 'complete' | 'partial';
  totalDistanceMeters: number;
  totalDurationSeconds: number;
  tripId: string;
  unlocatedActivityIds: Array<string>;
}
