/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DraftActivityDto {
  estimatedCost?: number;
  id: string;
  kind: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  notes: string;
  selected: boolean;
  time: string;
  title: string;
}
