/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DraftActivityDto } from '../models/draft-activity-dto';
export interface DraftDayDto {
  activities: Array<DraftActivityDto>;
  date: string;
}
