/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateItineraryDto {
  budget?: number;
  interests: Array<string>;
  pace: 'relajado' | 'equilibrado' | 'intenso';
  savedPlaceIds: Array<string>;
}
