/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeocodeResultDto } from '../models/geocode-result-dto';
export interface GeocodeSearchResponseDto {
  results: Array<GeocodeResultDto>;
  stale: boolean;
}
