/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GoogleLoginDto {

  /**
   * Credential emitido por Google Identity Services
   */
  credential: string;

  /**
   * Necesaria únicamente al crear una cuenta nueva
   */
  invitationToken?: string;
}
