/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitationResponseDto {
  active: boolean;
  consumed: boolean;
  createdAt: string;
  delivered?: boolean;
  email: string;
  expiresAt: string;
  id: string;
  url?: string;
}
