/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityResponseDto } from '../models/activity-response-dto';
export interface ItineraryDayResponseDto {
  activities: Array<ActivityResponseDto>;
  date: string;
  id: string;
  tripId: string;
}
