/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LegalDocumentDto } from '../models/legal-document-dto';
export interface LegalDocumentsResponseDto {
  currentVersion: string;
  documents: Array<LegalDocumentDto>;
}
