/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LegalSectionDto } from '../models/legal-section-dto';
export interface LegalDocumentDto {
  effectiveDate: string;
  key: string;
  sections: Array<LegalSectionDto>;
  title: string;
  version: string;
}
