/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalDayDto } from '../models/local-day-dto';
import { LocalExpenseDto } from '../models/local-expense-dto';
import { LocalPlaceDto } from '../models/local-place-dto';
import { LocalTripDto } from '../models/local-trip-dto';
export interface LocalImportDto {
  days: Array<LocalDayDto>;
  expenses: Array<LocalExpenseDto>;
  places: Array<LocalPlaceDto>;
  trips: Array<LocalTripDto>;
  version: number;
}
