/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {

  /**
   * Invitación privada de un solo uso
   */
  invitationToken: string;
  name: string;

  /**
   * Mínimo 8 caracteres, con al menos una mayúscula y un símbolo
   */
  password: string;
}
