/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordDto {

  /**
   * Mínimo 8 caracteres, con al menos una mayúscula y un símbolo
   */
  password: string;
  token: string;
}
