/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RouteGeometryDto } from '../models/route-geometry-dto';
export interface RouteLegResponseDto {
  availableSeconds?: number | null;
  distanceMeters: number;
  durationSeconds: number;
  fromActivityId: string;
  geometry: RouteGeometryDto;
  mode: 'walking' | 'cycling' | 'driving';
  scheduleStatus: 'ok' | 'conflict' | 'invalid-order';
  toActivityId: string;
}
