/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SavedPlaceResponseDto {
  address?: string | null;
  category: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  city: string;
  country: string;
  id: string;
  image?: string | null;
  imageAssetId?: string | null;
  imageVerified: boolean;
  latitude?: number | null;
  longitude?: number | null;
  name: string;
  note: string;
  visited: boolean;
}
