/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionResponseDto {
  current: boolean;
  expiresAt: string;
  id: string;
  lastUsedAt: string;
  startedAt: string;
  userAgent?: string;
}
