/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SharedTripDayResponseDto } from '../models/shared-trip-day-response-dto';
import { SharedTripPlaceResponseDto } from '../models/shared-trip-place-response-dto';
export interface SharedTripResponseDto {
  dates: {
} | null;
  days: Array<SharedTripDayResponseDto>;
  expiresAt: string;
  id: string;
  mapEnabled: boolean;
  places: Array<SharedTripPlaceResponseDto>;
  summary: {
} | null;
}
