/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SharedTripActivityResponseDto {
  address?: {
} | null;
  id: string;
  kind: string;
  latitude?: {
} | null;
  locationName?: {
} | null;
  longitude?: {
} | null;
  position: number;
  time: string;
  title: string;
}
