/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SharedTripActivityResponseDto } from '../models/shared-trip-activity-response-dto';
export interface SharedTripDayResponseDto {
  activities: Array<SharedTripActivityResponseDto>;
  date: string;
  id: string;
}
