/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SharedTripPlaceResponseDto {
  address?: {
} | null;
  category: string;
  city: string;
  country: string;
  id: string;
  image: {
} | null;
  latitude?: {
} | null;
  longitude?: {
} | null;
  name: string;
}
