/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItineraryDayResponseDto } from '../models/itinerary-day-response-dto';
import { SavedPlaceResponseDto } from '../models/saved-place-response-dto';
export interface TripMapResponseDto {
  days: Array<ItineraryDayResponseDto>;
  places: Array<SavedPlaceResponseDto>;
}
