/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TripResponseDto {
  budget: number;
  country: string;
  coverAssetId?: string | null;
  coverImage?: string | null;
  coverVerified: boolean;
  description: string;
  destination: string;
  endDate: string;
  id: string;
  startDate: string;
  status: 'planificando' | 'proximo' | 'completado';
}
