/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TripShareRecipientResponseDto } from '../models/trip-share-recipient-response-dto';
export interface TripShareResponseDto {
  active: boolean;
  createdAt: string;
  dayIds: Array<string>;
  expiresAt: string;
  id: string;
  placeIds: Array<string>;
  recipients: Array<TripShareRecipientResponseDto>;
  revokedAt: {
} | null;
  showDates: boolean;
  showMap: boolean;
  showSummary: boolean;
}
