/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTripDto {
  budget?: number;
  country?: string;
  coverImage?: string;
  description?: string;
  destination?: string;
  endDate?: string;
  startDate?: string;
  status?: 'planificando' | 'proximo' | 'completado';
}
