/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateActivityDto {
  completed?: boolean;
  cost?: number;
  kind?: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  notes?: string;
  time?: string;
  title?: string;
}
