/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTripShareDto {
  dayIds?: Array<string>;
  placeIds?: Array<string>;
  recipientEmails?: Array<string>;
  showDates?: boolean;
  showMap?: boolean;
  showSummary?: boolean;
}
