/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSavedPlaceDto {
  address?: string | null;
  category?: 'comida' | 'cultura' | 'naturaleza' | 'traslado' | 'alojamiento' | 'otro';
  city?: string;
  country?: string;
  image?: string;
  latitude?: number | null;
  longitude?: number | null;
  name?: string;
  note?: string;
  visited?: boolean;
}
