/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponseDto {
  email: string;
  emailVerified: boolean;
  id: string;
  name: string;
  providers: Array<'LOCAL' | 'GOOGLE'>;
}
