/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DayRouteResponseDto } from '../../models/day-route-response-dto';

export interface RoutingControllerDayRoute$Params {
  tripId: string;
  dayId: string;
}

export function routingControllerDayRoute(http: HttpClient, rootUrl: string, params: RoutingControllerDayRoute$Params, context?: HttpContext): Observable<StrictHttpResponse<DayRouteResponseDto>> {
  const rb = new RequestBuilder(rootUrl, routingControllerDayRoute.PATH, 'get');
  if (params) {
    rb.path('tripId', params.tripId, {});
    rb.path('dayId', params.dayId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DayRouteResponseDto>;
    })
  );
}

routingControllerDayRoute.PATH = '/trips/{tripId}/days/{dayId}/route';
