/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReauthenticateDto } from '../../models/reauthenticate-dto';
import { ReauthenticationResponseDto } from '../../models/reauthentication-response-dto';

export interface AuthControllerReauthenticate$Params {
      body: ReauthenticateDto
}

export function authControllerReauthenticate(http: HttpClient, rootUrl: string, params: AuthControllerReauthenticate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReauthenticationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerReauthenticate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReauthenticationResponseDto>;
    })
  );
}

authControllerReauthenticate.PATH = '/auth/reauthenticate';
