/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailActionDto } from '../../models/email-action-dto';
import { PendingAuthResponseDto } from '../../models/pending-auth-response-dto';

export interface AuthControllerForgotPassword$Params {
      body: EmailActionDto
}

export function authControllerForgotPassword(http: HttpClient, rootUrl: string, params: AuthControllerForgotPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<PendingAuthResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerForgotPassword.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PendingAuthResponseDto>;
    })
  );
}

authControllerForgotPassword.PATH = '/auth/forgot-password';
