/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountExportDto } from '../../models/account-export-dto';

export interface AccountControllerExport$Params {
}

export function accountControllerExport(http: HttpClient, rootUrl: string, params?: AccountControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountExportDto>> {
  const rb = new RequestBuilder(rootUrl, accountControllerExport.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountExportDto>;
    })
  );
}

accountControllerExport.PATH = '/me/export';
