/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateProfileDto } from '../../models/update-profile-dto';
import { UserResponseDto } from '../../models/user-response-dto';

export interface AccountControllerUpdateProfile$Params {
      body: UpdateProfileDto
}

export function accountControllerUpdateProfile(http: HttpClient, rootUrl: string, params: AccountControllerUpdateProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, accountControllerUpdateProfile.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponseDto>;
    })
  );
}

accountControllerUpdateProfile.PATH = '/me/profile';
