/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountDataDto } from '../../models/account-data-dto';

export interface DataControllerData$Params {
}

export function dataControllerData(http: HttpClient, rootUrl: string, params?: DataControllerData$Params, context?: HttpContext): Observable<StrictHttpResponse<AccountDataDto>> {
  const rb = new RequestBuilder(rootUrl, dataControllerData.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccountDataDto>;
    })
  );
}

dataControllerData.PATH = '/me/data';
