/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SavedPlaceResponseDto } from '../../models/saved-place-response-dto';
import { UpdateSavedPlaceDto } from '../../models/update-saved-place-dto';

export interface PlacesControllerUpdate$Params {
  placeId: string;
      body: UpdateSavedPlaceDto
}

export function placesControllerUpdate(http: HttpClient, rootUrl: string, params: PlacesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SavedPlaceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, placesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('placeId', params.placeId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SavedPlaceResponseDto>;
    })
  );
}

placesControllerUpdate.PATH = '/places/{placeId}';
